### ISSUE TITLE
Peer review by Ruizi Liu

### ISSUE THREAD

**Issue by RIRI0527** [alizamithwani/PollinateTO#3]
#### **Summary**
The paper investigates funding patterns in Toronto's PollinateTO initiative, focusing on the relationship between garden characteristics and funding allocations. By employing a Bayesian logistic regression model, the study identifies trends and patterns in urban greening efforts. The findings have significant implications for biodiversity, community equity, and resource optimization.

**Strengths:**
- **Topic Relevance:** The project aligns with current ecological and urban planning challenges, making it highly relevant.
- **Use of Bayesian Models:** The choice of Bayesian logistic regression is appropriate for understanding funding likelihoods and provides valuable uncertainty quantification.
- **Data Source:** The use of the publicly available PollinateTO Primary Project Garden Locations dataset ensures transparency and reproducibility.

**Critical Improvements Needed:**
- Include detailed justifications for modeling choices, specifically the Bayesian framework, and consider alternative methods.
- Ensure cross-references in the figures and text are fully functional.
- Enhance captions to make figures interpretable independently.

#### **Core Requirements**
1. **R/Python Cited**: **1/1**
   - R is properly cited in both the text and references.
   - Excellent use of `rstanarm` and `tidyverse` packages.

2. **Data Cited**: **1/1**
   - The dataset is correctly cited as sourced from the Toronto Open Data Portal.
   - The data's accessibility ensures transparency.

3. **Class Paper**: **1/1**
   - No signs indicate this is a class project.

4. **LLM Documentation**: **1/1**
   - The README includes a clear section documenting the use of ChatGPT.

#### **Paper Sections**
1. **Title**: **2/2**
   - Informative and relevant, clearly outlining the study's focus.

2. **Author, Date, and Repo**: **2/2**
   - Author details, submission date, and GitHub repository link are included.

3. **Abstract**: **3/4**
   - The abstract summarizes the study but lacks explicit details on key findings.
   - Suggestion: Include specific results for a stronger impact.

4. **Introduction**: **4/4**
   - Provides context, highlights the study’s significance, and outlines the structure.

5. **Estimand**: **1/1**
   - Clearly stated as the relationship between garden characteristics and funding.

6. **Data**: **8/10**
   - Data features and variables are well-described, but data cleaning processes need more detail.
   - Suggestion: Discuss challenges and transformations applied during preprocessing.

7. **Measurement**: **4/4**
   - Measurements and data attributes are well-justified.

8. **Model**: **6/10**
   - The Bayesian logistic regression is appropriate, but alternative models are not explored.
   - Suggestions:
     - Discuss why specific variables were included.
     - Add limitations of the model.
     - Mention the software used.

9. **Results**: **8/10**
   - Well-presented with meaningful visualizations.
   - Suggestion: Expand figure captions and ensure all tables use consistent formatting.

10. **Discussion**: **8/10**
    - Connects findings to broader implications but could benefit from additional citations.
    - Suggestion: Highlight actionable insights for policymakers more explicitly.

11. **Prose**: **5/6**
    - The writing is clear and professional, with minor typographical errors.

12. **Cross-references**: **1/1**
    - Cross-references are present but need fixing for some figures.

13. **Captions**: **1/2**
    - Captions lack detail and clarity.
    - Suggestion: Ensure captions explain figures without requiring additional context.

14. **Graphs/Tables**: **4/4**
    - Graphs are well-designed and informative.

15. **Surveys, Sampling, and Observational Data Appendix**: **0/10**
    - Not included.
    - Suggestion: Add an idealized methodology for community surveys.

16. **Referencing**: **4/4**
    - All references are correctly formatted.

17. **Commits**: **2/2**
    - Multiple meaningful commits with clear messages.

18. **Sketches**: **2/2**
    - Included and relevant.

19. **Simulation**: **3/4**
    - Interaction effects are not fully explored in the simulation.

20. **Tests**: **2/4**
    - Limited test coverage; consider using `testthat`.

21. **Parquet**: **0/1**
    - Data is not saved as Parquet.
    - Suggestion: Use the `arrow` package for efficiency.

22. **Reproducible Workflow**: **4/4**
    - Workflow is well-organized and documented.

23. **Enhancements**: **4/4**
    - Includes a datasheet and model card.

24. **Miscellaneous**: **3/3**
    - Repository is clean and well-maintained.

### **Suggestions for Improvement**
1. **Model Justification**:
   - Discuss alternative models and justify the Bayesian approach in greater depth.
   - Include situations where the model may not apply.

2. **Appendix**:
   - Add an idealized survey design to explore potential enhancements.

3. **Captions**:
   - Improve figure and table captions for standalone clarity.

4. **Use Parquet Format**:
   - Save cleaned data using the `arrow` package for better compatibility and performance.

### **Overall Comments**
This is a strong and well-structured submission with a clear research focus. Minor refinements in methodology, results presentation, and appendix content could elevate the paper further. Great effort!

**Comment by alizamithwani** [comment]
Thank you for your feedback!
